### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by cgilling** [chrisport/go-lang-detector#1]
Hi,

Just had a few questions I was hoping you could answer:

1. What languages are supported by default?
2. Have you run comparisons against other open source language detectors to see how much different the results are?
3. Have you benchmarked the performance of this against other open source language detectors in terms of speed?

Thanks

**Comment by chrisport** [comment]
Hi cgilling,

1. The default language file includes Arabic, English, French, German, Hebrew, Russian and Turkish.

2./3. I did some comparisons, but since I didn't document them I cannot make a profound statement now, so here just what I remember, nothing granted, no numbers:

With the default-level of 70% I had comparable results with https://github.com/pebbe/textcat.
Performance-wise textcat was slightly faster. You can adjust confidence-level of the Detector easily, higher means less false-positive, but more false-negative, lower means other way round.

If you need higher performance you can decrease nDepth-level, but it will decrease accuracy (though not drastically). nDepth = 1 means basically comparing letter frequency. The default-languages must be recreated in this case with same nDepth.

Further experience: We were using https://github.com/pebbe/libtextcat in a project, but had problems if the text is mixed (2 or more languages). With go-lang-detector I experienced better results on the same dataset.

If you are interested in creating a comparison, I will happily contribute.
