### ISSUE TITLE
Add Chinese in language detection

### ISSUE THREAD

**Issue by RajeshKumar1990** [chrisport/go-lang-detector#13]
Will it be possible to direct me how to detect the language written in chinese.I searched everywhere but couldnt find the Chinese  text sample to add the language  in the detector.Thanks

**Comment by chrisport** [comment]
To add any language, you can just let langdet analyze an arbitrary text. The longer the better:
```
	detector.AddLanguageFromText(GetTextFromFile("samples/chinese.txt"), "chinese")
```
For chinese.txt I just copied the content of this article: https://zh-classical.wikipedia.org/wiki/%E4%B8%AD%E8%8F%AF%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9C%8B
Result for "夫大典也，自許曰：「海納百川":
```
GetClosestLanguage returns:
      undefined
GetLanguages returns:
     chinese 64 %
     english 0 %
     french 0 %
     turkish 0 %
...
```
My chinese.txt is bit short and results were not convincing. I'm not sure how well Chinese will work even with a longer text, since there are many characters and the tokens therefore do not repeat often. 
If you have a longer text, please share your results.

**Comment by chrisport** [comment]
I plan to implement an interface around the Detector and write decorators for special cases such as Chinese.
