### ISSUE TITLE
Low confidence on Russian language

### ISSUE THREAD

**Issue by skar404** [chrisport/go-lang-detector#21]
Code:
```go
package main

import (
	"os"
	"strings"

	"github.com/chrisport/go-lang-detector/langdet/langdetdef"
)

func main() {
	arg := strings.Join(os.Args[1:], " ")

	detector := langdetdef.NewWithDefaultLanguages()
	result := detector.GetClosestLanguage(arg)
	fmt.Println(arg, ' is ', result)
}
```

Print: `привет мир is undefined`, `привет мир` is Russian lang.

**Comment by chrisport** [comment]
It seems this small text snippet is not enough with the default language. If you check the confidence levels:
`привет мир  is  [{russian 27} {CJK 0} {hebrew 0} {arabic 0} {english 0} {german 0} {french 0} {turkish 0}]`
There are two solutions:
1. You can lower the MininumConfidence like this to receive 'russian' as the result:
```
	detector := langdetdef.NewWithDefaultLanguages()
	detector.MinimumConfidence=0.25
	result := detector.GetClosestLanguage(arg)
	fmt.Println(arg, " is ", result)
```
2. You can add a comparator using unicode:
```
detector.AddLanguageComparators(&langdet.UnicodeRangeLanguageComparator{"cyrillic", unicode.Cyrillic})
```
This will result in `привет мир  is  [{cyrillic 90} {russian 27} {CJK 0} {hebrew 0} {english 0} {german 0} {french 0} {turkish 0} {arabic 0}]`

I recommend you use the second method if knowing that it is cyrillic is sufficient, since there are [other languages using this alphabet](https://en.wikipedia.org/wiki/Cyrillic_alphabets).
I will look into improving default detection of Russian, maybe it will be good to look at the unicode as well.
