### ISSUE TITLE
Guesses english as higher probability with estonian phrase

### ISSUE THREAD

**Issue by wolfgangmeyers** [chrisport/go-lang-detector#4]
Hello,

I loaded the default lang detector with an Estonian dictionary, then tested a list of keywords from an Estonian web page. The lang detector guesses English as a higher probability than Estonian, even though only one of the keywords is also English (as far as I know). Keywords are "domeen registreeritud see kuid saab"

Anything I can do differently to help the detector guess the correct language here?

Minimal example code to reproduce the issue on dropbox: https://www.dropbox.com/s/z05ct7eowp3yq9m/langtest.zip?dl=0

**Comment by chrisport** [comment]
Hi, thank you for the upload, I will also test it out.
Please be aware that it is a bad idea to use a Dictionary, because the frequency of a token in the dictionary is not representing the frequency in an Estonian text. Just imagine the English word "the", which would appear many  times in an English text, but in the dictionary it appears only once.

**Comment by wolfgangmeyers** [comment]
That's what I needed to know. Thanks!
